<?php

namespace Test\Lib\XML;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-24 at 22:14:21.
 */
class XMLConfigReaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var XMLConfigReader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new XMLConfigReader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers App\Lib\XML\XMLConfigReader::setFilePath
     * @todo   Implement testSetFilePath().
     */
    public function testSetFilePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Lib\XML\XMLConfigReader::getElementData
     * @todo   Implement testGetElementData().
     */
    public function testGetElementData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Lib\XML\XMLConfigReader::getElementDataByAttr
     * @todo   Implement testGetElementDataByAttr().
     */
    public function testGetElementDataByAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Lib\XML\XMLConfigReader::getXMLData
     * @todo   Implement testGetXMLData().
     */
    public function testGetXMLData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
